name: PackageBot

on:
  push:
    branches: ["repo"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unstable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Update Unstable on Repo
        shell: bash
        run: |
          git pull
          gh release -R pbskids-dl/pbskids-dl download unstable --pattern '*.deb'
          rm ./pool/main/unstable/pbskids-dl_unstable-*_all.deb
          mv pbskids-dl_debian.deb ./pool/main/unstable/pbskids-dl_unstable-$(($RANDOM))_all.deb
          ./generate_packages_unstable.sh
          cd ./dists/unstable
          ./generate-release.sh > main/Release
          cd ../..
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "[PackageBot] Update Unstable Packages"
          git push
        env:
          GH_TOKEN: ${{ github.token }}
  stable:
    needs: unstable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Update Stable on Repo
        shell: bash
        run: |
          git pull
          gh release -R pbskids-dl/pbskids-dl download --pattern '*.deb'
          rm ./pool/main/stable/pbskids-dl_?.?.?-1_all.deb
          DEB_VERSION=`curl -s https://raw.githubusercontent.com/pbskids-dl/pbskids-dl_debian/build/version`
          mv pbskids-dl_debian.deb ./pool/main/stable/pbskids-dl_$(($DEB_VERSION))-1_all.deb
          ./generate-packages.sh
          cd ./dists/stable
          ./generate-release.sh > main/Release
          cd ../..
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "[PackageBot] Update Stable Packages" || true
          git push
        env:
          GH_TOKEN: ${{ github.token }}