name: Build Unstable

on:
  push:
    branches: ["repo"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Add Unstable to Repos
        shell: bash
        run: |
          gh release -R pbskids-dl/pbskids-dl download unstable --pattern '*.deb'
          rm ./pool/main/unstable/pbskids-dl_unstable-*_all.deb
          mv pbskids-dl_debian.deb ./pool/main/unstable/pbskids-dl_unstable-$(($RANDOM))_all.deb
          ./generate_packages_unstable.sh
          cd ./dists/unstable
          ./generate-release.sh > main/binary-all/Release
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add . -f
          git commit -m "Update unstable"
          git push
        env:
          GH_TOKEN: ${{ github.token }}
