name: update and deploy

on:
  push:
    branches: ["repo"]
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  packagebot:
    uses: pbskids-dl/apt/.github/workflows/packagebot.yml@repo
  deploy:
    needs: packagebot
    uses: pbskids-dl/apt/.github/workflows/deploy.yml@repo